trigger:
  branches:
    include:
      - main  # Trigger the pipeline on the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu-based agent

steps:
  # Step 1: Checkout the repository
  - task: Checkout@2
    displayName: 'Checkout code'

  # Step 2: Set up Python
  - task: UsePythonVersion@0
    displayName: 'Set up Python'
    inputs:
      versionSpec: '3.8'  # Use Python version 3.8

  # Step 3: Install dependencies
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  # Step 4: Run tests
  - script: |
      pytest
    displayName: 'Run tests'

  # Step 5: Build the application (optional)
  - script: |
      python setup.py install
    displayName: 'Build application'
